const SUPPORT_ARTICLE_URL = 'https://www.1do.io/';

const ZENDESK_URLS = {
  ACCOUNT_UPGRADE: SUPPORT_ARTICLE_URL,
  ADD_CUSTOM_TOKENS: SUPPORT_ARTICLE_URL,
  ADD_SOLANA_ACCOUNTS: SUPPORT_ARTICLE_URL,
  CUSTOMIZE_NONCE: SUPPORT_ARTICLE_URL,
  GAS_FEES: SUPPORT_ARTICLE_URL,
  HARDWARE_CONNECTION: SUPPORT_ARTICLE_URL,
  HARDWARE_CONNECTION_TREZOR_LEDGER: SUPPORT_ARTICLE_URL,
  IMPORT_ACCOUNT_MOBILE: SUPPORT_ARTICLE_URL,
  IMPORTED_ACCOUNTS: SUPPORT_ARTICLE_URL,
  IMPORTED_ACCOUNT_JSON: SUPPORT_ARTICLE_URL,
  IMPORTED_ACCOUNTS_PRIVATE_KEY: SUPPORT_ARTICLE_URL,
  INFURA_BLOCKAGE: SUPPORT_ARTICLE_URL,
  LEDGER_FIREFOX_U2F_GUIDE:
    'https://support.ledger.com/hc/en-us/articles/10371387758493-MetaMask-Firefox-Ledger-Integration-Issue?support=true',
  LEGACY_WEB3: SUPPORT_ARTICLE_URL,
  PASSWORD_ARTICLE: SUPPORT_ARTICLE_URL,
  PASSWORD_AND_SRP_ARTICLE: SUPPORT_ARTICLE_URL,
  PRIVATE_KEY_GUIDE: SUPPORT_ARTICLE_URL,
  PASSWORD_RESET: SUPPORT_ARTICLE_URL,
  SECRET_RECOVERY_PHRASE: SUPPORT_ARTICLE_URL,
  NON_CUSTODIAL_WALLET: SUPPORT_ARTICLE_URL,
  SPEEDUP_CANCEL: SUPPORT_ARTICLE_URL,
  SUPPORT_URL: SUPPORT_ARTICLE_URL,
  TOKEN_SAFETY_PRACTICES: SUPPORT_ARTICLE_URL,
  UNKNOWN_NETWORK: SUPPORT_ARTICLE_URL,
  USER_GUIDE_CUSTOM_NETWORKS: SUPPORT_ARTICLE_URL,
  USER_GUIDE_DAPPS: SUPPORT_ARTICLE_URL,
  USER_GUIDE_GAS: SUPPORT_ARTICLE_URL,
  VERIFY_CUSTOM_NETWORK: SUPPORT_ARTICLE_URL,
  NETWORK_DEPRECATED: SUPPORT_ARTICLE_URL,
  SOLANA_ACCOUNTS: SUPPORT_ARTICLE_URL,
  METAMETRICS_SETTINGS: SUPPORT_ARTICLE_URL,
  PROFILE_PRIVACY: SUPPORT_ARTICLE_URL,
  CONTRACT_ADDRESS_WARNING: SUPPORT_ARTICLE_URL,
  FIND_TRANSACTION_HASH: SUPPORT_ARTICLE_URL,
  MULTICHAIN_ACCOUNTS: SUPPORT_ARTICLE_URL,
  CONNECTING_TO_DAPP: SUPPORT_ARTICLE_URL,
  PRIVACY_BEST_PRACTICES: SUPPORT_ARTICLE_URL,
  BASIC_SAFETY_TIPS: SUPPORT_ARTICLE_URL,
  DECEPTIVE_SITE: SUPPORT_ARTICLE_URL,
  UPDATE_VERSION: SUPPORT_ARTICLE_URL as const,
} as const;

export type ZendeskUrl = (typeof ZENDESK_URLS)[keyof typeof ZENDESK_URLS];

export default ZENDESK_URLS;
